{% set name = "rvlib" %}
{% set version = "0.0.5" %}
{% set sha1 = "aa18c192a7bdc44e3c6998795da9fc7b988d12d9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantEcon/rvlib/archive/v{{ version }}.tar.gz
  sha1: {{ sha1 }}

build:
  skip: true  # [win]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.5
    - pip
    - cffi
    - pyyaml

  run:
    - python >=3.5
    - numpy
    - cffi
    - numba
    - pyyaml

test:
  imports:
    - rvlib

about:
  home: https://github.com/QuantEcon/rvlib
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Mimicking the API of Distributions.jl in Python with added numba support.
  description: |
    rvlib is a statistical package that mimics the API of Julia's
    Distributions.jl package while at the same time achieves a similar
    performance by exploiting numba.
  dev_url: https://github.com/QuantEcon/rvlib

extra:
  recipe-maintainers:
    - danielcsaba
    - sglyon
