{% set name = "rvlib" %}
{% set version = "0.0.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d79b45bedff32653ed4662da1a273d3b3d70ea960ad4fd8d74509888d7f7f45d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}

  host:
    - python
    - setuptools
    - pip
    - cffi
    - pyyaml
    - numpy
    - m2w64-gcc                              # [win]
    - libpython                              # [win]

  run:
    - python
    - numpy
    - cffi
    - numba >=0.49
    - pyyaml

test:
  imports:
    - rvlib

about:
  home: https://github.com/QuantEcon/rvlib
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Mimicking the API of Distributions.jl in Python with added numba support.'
  description: |
    rvlib is a statistical package that mimics the API of Julia's
    Distributions.jl package while at the same time achieves a similar
    performance by exploiting numba.
  dev_url: https://github.com/QuantEcon/rvlib

extra:
  recipe-maintainers:
    - knaaptime
    - danielcsaba
    - sglyon
