{% set version = "0.0.6" %}

package:
  name: rvlib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rvlib/rvlib-{{ version }}.tar.gz
  sha256: 05a4bbb74386ed083900029a8ef6f19d913d8e02dc997b409f4097f731d6918f

build:
  number: 5
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - cffi                                   # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}                    # [not win]
    - {{ stdlib("c") }}                      # [not win]
    - {{ compiler('m2w64_c') }}              # [win]
    - {{ stdlib("m2w64_c") }}                # [win]
  host:
    - python
    - setuptools
    - pip
    - cffi
    - pyyaml
    - numpy
    - libpython                              # [win]
  run:
    - python
    - numpy
    - cffi
    - numba >=0.49
    - pyyaml

test:
  imports:
    - rvlib

about:
  home: https://github.com/QuantEcon/rvlib
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Mimicking the API of Distributions.jl in Python with added numba support.'
  description: |
    rvlib is a statistical package that mimics the API of Julia's
    Distributions.jl package while at the same time achieves a similar
    performance by exploiting numba.
  dev_url: https://github.com/QuantEcon/rvlib

extra:
  recipe-maintainers:
    - knaaptime
    - danielcsaba
    - sglyon
