travis:
  secure:
    BINSTAR_TOKEN: Pyp6OtORtvb8ycMFxRihZtyVGD3Fv+zoPnaIfbOrzO0Wkpi7ryFry1YUrKtOXxUdNMFOvdrWtr9Du9f0WbUNkvR/3TnD6Ur31cbowQJlH9mQX7x3eyRYvSEMJPWs0BVAmccFU9Tdacg0+bF7lHNsVbfin+co/mM0/9TWmOnl3t/NvZIqIea8YMonZzfPS5N8X7YvqfoI7O7PcAl+VR0BhC5qQ7hE6Bs2Obcrg55PndfFk3Zo9A/o2NetDCA1B3tA4mlv7i/iCCHwmavoX0DXAIHXB1mzTA6eX0Yuo0MXyRlda/ocDopjr8sSO47PCHeu50lplr329dP5TSRkiLSz9YuxnSGKuBQfqlL13t1k97v0NbSuiLvKt1dPBCA+i330rQuK1wXygYVLcfApSmvypbFk4qe0XKyVHijjt7+2+duXPBbJcq62pCLYKjL12AgbQdily2bivviBOPNSGqTulVYLsYCjvWyWbMh5x0vj575lAuqYY5vELsrjSRsk4ywmfe9wAceNzLTSCSz6Y1hS/1qyFVVsClLvtIpi0S+BNHZsz7qkffa3Ppa8AP6GwUKfYnrTlhBdr9r9vJ0JovmxyeCOwxHQktFENohJ1IdoSftmAuIVNHv8u0t3zzFnkD5Qds586pwR3rNQ5WFg0P/0c1PE1ZDD0m/IT6Z8im6YImE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
