appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Eorzxe5Q7e061PfV9HsbkLqd1XmP8sxZGpyW6aJ2AxsIt2QqwSDKAYYJ+jtvUi4YP3/iDOzTcbMwAhWozqtB6v2BfklYHgg+iNhmOvmKHK0K9nKw8dKpCqznPoIHMM77iUnmvk/dwKNxsa4HfaR7eP8B4UVzcPzcuHhm7c+zD8WJ6Jw484owDylDYzEaKq5S2kV45AnSFsDpADgo4wfTXy5Hw+4gnYiD5GxQN396d1mMf6nFb4L/8ctTYcwZPuvLoN0G+WAGf+O3IKHm3lwgdySaiIBN7YYn4FyD7jl0IHmgtZENitQa794iIghl5SenEyfLi9Cy5d6MxWomJU6/uLZI9np45V7Dr3LV53RUPllTmDsO2YAMwrI+esv5s5w6FO7ANpPiqwx4TymjcCkBsQfTnLSZs2B1joWXw1uQLPEXRX9sMmLrE+Ehxvwkwo5Sma/gq92r8M4TERZbl7rXQdEGVFWle5+SIz8AkI/DolRETfc0rZltCwupPeOUQnH7p9Mjn5I0pxa7HR1lTwIVYAQLKqTpJig12DNmVuvkiVIwNmH6yf4HG04ZwDEXJv7robDZc4MpELfOVtCUjE4FO0V1ME0i8tDrdODaWNi8mMi7j6f7DocRU8wR8CbHJEsY9qnHdcs8wtEuyO6dlEj2ef6Se6cMOUiDlVN7qZPWHhQ=}
conda_forge_output_validation: true
